// Package shellenv maintains YAPP's per-user shell PATH configuration.
package shellenv

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	beginMarker = "# >>> yapp managed >>>"
	endMarker   = "# <<< yapp managed <<<"
	maxRCSize   = 1 << 20
)

// Detect returns the user's configured interactive shell name.
func Detect() (string, error) {
	shell := filepath.Base(os.Getenv("SHELL"))
	switch shell {
	case "bash", "zsh":
		return shell, nil
	case "":
		return "", fmt.Errorf("SHELL is not set; set it to bash or zsh before installing")
	default:
		return "", fmt.Errorf("unsupported shell %q; YAPP currently supports bash and zsh", shell)
	}
}

// Configure writes a sourced environment file under ~/.yapp and adds one
// managed source block to the user's selected shell startup file. The operation
// is safe to repeat.
func Configure(userHome, shell, installPath string) error {
	if shell != "bash" && shell != "zsh" {
		return fmt.Errorf("unsupported shell %q", shell)
	}
	if !safeRelativePath(installPath) {
		return fmt.Errorf("unsafe YAPP install path %q", installPath)
	}

	yappHome := filepath.Join(userHome, ".yapp")
	info, err := os.Lstat(yappHome)
	if err != nil {
		return fmt.Errorf("inspect YAPP home: %w", err)
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("YAPP home must be a real directory: %s", yappHome)
	}

	envPath := filepath.Join(yappHome, "yapp-env.sh")
	envContent := fmt.Sprintf(`# Generated by YAPP. Local edits may be overwritten.
export YAPP_HOME="${HOME}/.yapp"
export JAVA_HOME="${YAPP_HOME}/%s"
case ":${PATH:-}:" in
  *":${JAVA_HOME}/bin:"*) ;;
  *) export PATH="${JAVA_HOME}/bin${PATH:+:${PATH}}" ;;
esac
`, filepath.ToSlash(installPath))
	if err := atomicWrite(envPath, []byte(envContent), 0o600); err != nil {
		return fmt.Errorf("write YAPP shell environment: %w", err)
	}

	rcName := ".bashrc"
	if shell == "zsh" {
		rcName = ".zshrc"
	}
	rcPath := filepath.Join(userHome, rcName)
	existing, err := os.ReadFile(rcPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", rcName, err)
	}
	if len(existing) > maxRCSize {
		return fmt.Errorf("%s exceeds the maximum supported size", rcName)
	}
	containsBegin := strings.Contains(string(existing), beginMarker)
	containsEnd := strings.Contains(string(existing), endMarker)
	if containsBegin || containsEnd {
		if containsBegin && containsEnd && strings.Index(string(existing), beginMarker) < strings.Index(string(existing), endMarker) {
			return nil
		}
		return fmt.Errorf("%s contains an incomplete YAPP-managed block; repair it before installing", rcName)
	}

	block := fmt.Sprintf("\n%s\nif [ -r \"${HOME}/.yapp/yapp-env.sh\" ]; then\n  . \"${HOME}/.yapp/yapp-env.sh\"\nfi\n%s\n", beginMarker, endMarker)
	if len(existing)+len(block) > maxRCSize {
		return fmt.Errorf("adding YAPP integration would make %s too large", rcName)
	}
	flags := os.O_WRONLY | os.O_APPEND | os.O_CREATE
	file, err := os.OpenFile(rcPath, flags, 0o600)
	if err != nil {
		return fmt.Errorf("open %s: %w", rcName, err)
	}
	defer file.Close()
	info, err = file.Stat()
	if err != nil {
		return fmt.Errorf("inspect %s: %w", rcName, err)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s must be a regular file", rcName)
	}
	if _, err := file.WriteString(block); err != nil {
		return fmt.Errorf("update %s: %w", rcName, err)
	}
	if err := file.Sync(); err != nil {
		return fmt.Errorf("sync %s: %w", rcName, err)
	}
	return nil
}

func atomicWrite(path string, data []byte, mode os.FileMode) error {
	file, err := os.CreateTemp(filepath.Dir(path), ".yapp-env-*")
	if err != nil {
		return err
	}
	tempPath := file.Name()
	defer os.Remove(tempPath)
	if err := file.Chmod(mode); err != nil {
		_ = file.Close()
		return err
	}
	if _, err := file.Write(data); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	if err := os.Rename(tempPath, path); err != nil {
		return err
	}
	directory, err := os.Open(filepath.Dir(path))
	if err != nil {
		return err
	}
	defer directory.Close()
	return directory.Sync()
}

func safeRelativePath(value string) bool {
	if value == "" || filepath.IsAbs(value) || strings.Contains(value, `\`) {
		return false
	}
	for _, component := range strings.Split(filepath.ToSlash(value), "/") {
		if component == "" || component == "." || component == ".." {
			return false
		}
		for _, char := range component {
			if !(char >= 'a' && char <= 'z' || char >= 'A' && char <= 'Z' || char >= '0' && char <= '9' || strings.ContainsRune("._+-", char)) {
				return false
			}
		}
	}
	return true
}
