// Package shellenv maintains YAPP's per-user shell PATH configuration.
package shellenv

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sukumaar/yapp/internal/fileutil"
	"github.com/sukumaar/yapp/internal/validation"
)

const (
	beginMarker = "# >>> yapp managed >>>"
	endMarker   = "# <<< yapp managed <<<"
	maxRCSize   = 1 << 20
)

// Detect returns the user's configured interactive shell name.
func Detect() (string, error) {
	shell := filepath.Base(os.Getenv("SHELL"))
	switch shell {
	case "bash", "zsh":
		return shell, nil
	case "":
		return "", fmt.Errorf("SHELL is not set; set it to bash or zsh before installing")
	default:
		return "", fmt.Errorf("unsupported shell %q; YAPP currently supports bash and zsh", shell)
	}
}

// Configure writes a sourced environment file under ~/.yapp and adds one
// managed source block to the user's selected shell startup file. The operation
// is safe to repeat.
func Configure(userHome, shell string, variables map[string]string, pathEntries []string) error {
	if shell != "bash" && shell != "zsh" {
		return fmt.Errorf("unsupported shell %q", shell)
	}
	for name, value := range variables {
		if !validation.EnvironmentName(name) || !validation.SafeRelativePath(value) {
			return fmt.Errorf("unsafe YAPP environment variable setting %q", name)
		}
	}
	for _, path := range pathEntries {
		if !validation.SafeRelativePath(path) {
			return fmt.Errorf("unsafe YAPP PATH entry %q", path)
		}
	}

	yappHome := filepath.Join(userHome, ".yapp")
	info, err := os.Lstat(yappHome)
	if err != nil {
		return fmt.Errorf("inspect YAPP home: %w", err)
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("YAPP home must be a real directory: %s", yappHome)
	}

	envPath := filepath.Join(yappHome, "yapp-env.sh")
	var env strings.Builder
	env.WriteString(`# Generated by YAPP. Local edits may be overwritten.
export YAPP_HOME="${HOME}/.yapp"
`)
	variableNames := make([]string, 0, len(variables))
	for name := range variables {
		variableNames = append(variableNames, name)
	}
	sort.Strings(variableNames)
	for _, name := range variableNames {
		fmt.Fprintf(&env, "export %s=\"${YAPP_HOME}/%s\"\n", name, filepath.ToSlash(variables[name]))
	}
	// Prepend in reverse so dependency-first catalog order is preserved in PATH.
	for index := len(pathEntries) - 1; index >= 0; index-- {
		bin := "${YAPP_HOME}/" + filepath.ToSlash(pathEntries[index])
		fmt.Fprintf(&env, "case \":${PATH:-}:\" in\n  *\":%s:\"*) ;;\n  *) export PATH=\"%s${PATH:+:${PATH}}\" ;;\nesac\n", bin, bin)
	}
	if err := fileutil.AtomicWrite(envPath, []byte(env.String()), 0o600); err != nil {
		return fmt.Errorf("write YAPP shell environment: %w", err)
	}

	rcName := ".bashrc"
	if shell == "zsh" {
		rcName = ".zshrc"
	}
	rcPath := filepath.Join(userHome, rcName)
	existing, err := os.ReadFile(rcPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", rcName, err)
	}
	if len(existing) > maxRCSize {
		return fmt.Errorf("%s exceeds the maximum supported size", rcName)
	}
	containsBegin := strings.Contains(string(existing), beginMarker)
	containsEnd := strings.Contains(string(existing), endMarker)
	if containsBegin || containsEnd {
		if containsBegin && containsEnd && strings.Index(string(existing), beginMarker) < strings.Index(string(existing), endMarker) {
			return nil
		}
		return fmt.Errorf("%s contains an incomplete YAPP-managed block; repair it before installing", rcName)
	}

	block := fmt.Sprintf("\n%s\nif [ -r \"${HOME}/.yapp/yapp-env.sh\" ]; then\n  . \"${HOME}/.yapp/yapp-env.sh\"\nfi\n%s\n", beginMarker, endMarker)
	if len(existing)+len(block) > maxRCSize {
		return fmt.Errorf("adding YAPP integration would make %s too large", rcName)
	}
	flags := os.O_WRONLY | os.O_APPEND | os.O_CREATE
	file, err := os.OpenFile(rcPath, flags, 0o600)
	if err != nil {
		return fmt.Errorf("open %s: %w", rcName, err)
	}
	defer file.Close()
	info, err = file.Stat()
	if err != nil {
		return fmt.Errorf("inspect %s: %w", rcName, err)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s must be a regular file", rcName)
	}
	if _, err := file.WriteString(block); err != nil {
		return fmt.Errorf("update %s: %w", rcName, err)
	}
	if err := file.Sync(); err != nil {
		return fmt.Errorf("sync %s: %w", rcName, err)
	}
	return nil
}
